### ISSUE TITLE
stoped working today with viomi.vacuum.v8

### ISSUE THREAD

**Issue by radimsejk** [PiotrMachowski/Xiaomi-cloud-tokens-extractor#50] opened 2021-12-31 23:30 UTC
I have installed the Xiaomi Miot Auto to he Home Assistant and it worked with my robot until today. Now is the device unavailable. When I tried the python script for extracting cloud token, it says "unable to get devices". The vacuum is working normaly and I can see it or control it via the Mi Home app normaly.

**Comment by Tamsy** [comment] 2022-01-01 01:24
> I have installed the Xiaomi Miot Auto to he Home Assistant and it worked with my robot until today. Now is the device unavailable. When I tried the python script for extracting cloud token, it says "unable to get devices". The vacuum is working normaly and I can see it or control it via the Mi Home app normaly.

Did you lately update the Xiaomi Home app to the latest v.7? 

I did and since yesterday afternoon my 2 Roborock s5 max are unable to retrieve their maps anymore with Xiaomi Cloud Vacuum Map Extractor. Tried to recheck the tokens through token_extractor.exe (as admin) but nothing more than:

```
.....
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:
de

Logging in...
Logged in.

Unable to get devices.
Press ENTER to finish
```

Note that I am using the server for "de"

So I retried leaving "Server" empty to check on all Xiaomi Servers:

```
......
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:

Logging in...
Logged in.

No devices found for server "cn".
Unable to get devices.
No devices found for server "us".
No devices found for server "ru".
No devices found for server "tw".
No devices found for server "sg".
No devices found for server "in".
No devices found for server "i2".

Press ENTER to finish
```

Maybe the server for "de" is down (or even removed)?

What is strange is that the maps for the vacuums are showing in the Xiaomi Home app (after the maps where gone there too for a couple of hours).

**Comment by peterhoe** [comment] 2022-01-01 07:09
Looks like Xiaomi are having some problems with their server / cloud infrastructure

https://www.reddit.com/r/Xiaomi/comments/rsrwtk/eu_servers_31122022_not_working/

**Comment by Tamsy** [comment] 2022-01-01 07:27
> Looks like Xiaomi are having some problems with their server / cloud infrastructure

Thank you for the info. 

What worries me is that I can control both S5 Max through the Mi Home app (maps are showing) but they fail with HA. Lets hope Xiaomi fixes this any time soon.

**Comment by radimsejk** [comment] 2022-01-01 09:41
@Tamsy thank you for writing down every detail of this problem. Looks like we both have the same errors. I can too control my vacuum through the Mi Home app but HA cannot connect to it. I hope it is some bad luck new years git commit and it will be fixed soon :)

**Comment by fritanga** [comment] 2022-01-01 11:08
Same problem here with rockrobo_vacuum_v1, i'm also 'de' server.

**Comment by rezmus** [comment] 2022-01-01 11:43
they forced rc4 on eu cloud, it won't accept plain data anymore.

@PiotrMachowski you use rc4 by default now, because mi home use rc4 only for over a year so it's just matter of time other clouds will be switched to rc4 only.

https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/xiaomi_cloud.py

**Comment by Tamsy** [comment] 2022-01-01 12:43
@rezmus, thank you for clarifying. So we have to wait for @PiotrMachowski to update Xiaomi-cloud-tokens-extractor and xiaomi_cloud_map_extractor to access xiaomi cloud through rc4 to be able to get it back to work again?

**Comment by canedje** [comment] 2022-01-01 13:46
Ahh I do have the same problem. I don't know what rc4 means but I will wait

**Comment by Tamsy** [comment] 2022-01-01 13:49
> I don't know what rc4 means

RC4 (Rivest Cipher 4): https://en.wikipedia.org/wiki/RC4

**Comment by JelleMarc** [comment] 2022-01-02 12:11
Same issue here, following this thread for a fix :)

**Comment by lweberru** [comment] 2022-01-02 12:28
Same issue here.

**Comment by lweberru** [comment] 2022-01-02 12:29
Any alternative manual way to get the token?

**Comment by themsk666** [comment] 2022-01-02 13:00
Since 31 dec '20, DE server do now show token. At first the Mi home app was down too but now only the DE server not showing the token. Other region servers are working. HA intergration is not controling the vacuum.
Hope for a update soon.

**Comment by axcs** [comment] 2022-01-02 14:00
Same issue here. there is no way to add rc4?

**Comment by PricelessToolkit** [comment] 2022-01-02 14:36
Same issue here.

**Comment by PiotrMachowski** [comment] 2022-01-02 14:52
A fix is almost ready, it just needs some polishing

**Comment by r3pek** [comment] 2022-01-02 15:36
> A fix is almost ready, it just needs some polishing

damn.... I was working on it when you posted the message :( oh well.... feel free to close it if you want :P

**Comment by PiotrMachowski** [comment] 2022-01-02 15:50
@r3pek I got it working ~10h ago, but it was already 7AM and I decided that I finally need to get some sleep ;)

**Comment by r3pek** [comment] 2022-01-02 16:00
> @r3pek I got it working ~10h ago, but it was already 7AM and I decided that I finally need to get some sleep ;)

I just figured you were busy or something so I hacked a solution right fast :P

**Comment by sagitt** [comment] 2022-01-02 18:48
same here,
no calibraiton points

calibration_points: null

**Comment by PiotrMachowski** [comment] 2022-01-02 22:26
It should work now

**Comment by r3pek** [comment] 2022-01-02 22:30
Confirmed! Will you update your other repos today?

**Comment by PiotrMachowski** [comment] 2022-01-02 22:30
I think so :)

**Closed** 2022-01-02 22:31 UTC

**Comment by wind1980** [comment] 2022-01-02 22:35
Only for help I have the same problem to retrieving the map one of my two xiaomi robot (registred in DE server) in HA and also trying to verify the token (with token extractor app) i have this error whan i try to connect to DE server:

Logging in...
Logged in.

Unable to get devices.

Thanks for your work!

**Comment by r3pek** [comment] 2022-01-02 22:36
@wind1980 update to the latest version. @PiotrMachowski just updated the repo to make it work

**Comment by wind1980** [comment] 2022-01-02 22:41
Which version? I found the 2.1.1 in HACS  but with this one i have always the problem

**Comment by PiotrMachowski** [comment] 2022-01-02 22:43
@wind1980 this is a repo of Tokens Extractor, Map Extractor has not been updated yet

**Comment by r3pek** [comment] 2022-01-02 22:43
this is the token extractor repo mate ;) this one isn't on HACS... You're probably talking about https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor which he will update next (I think)

**Comment by wind1980** [comment] 2022-01-02 22:53
Sorry, i confused the token extractor app with the Xiaomi cloud extractor integration for HA!

Now the app extractor works with DE server again but i have the same token before for my S5 Max so i have the same problem in HA integration yet.
From the last HA update i have the message " failed to retrieve the model" in camera map preview.
Instead for my other Xiaomi vacuum ( model 1S) all continue to work fine like ever

**Comment by wind1980** [comment] 2022-01-02 22:56
> @wind1980 this is a repo of Tokens Extractor, Map Extractor has not been updated yet

Yes, 

> @wind1980 this is a repo of Tokens Extractor, Map Extractor has not been updated yet

Right, I noticed my mistake.

I'll wait for the update of xiaomi maps extractor integration HA.

Thanks for your great work again!

**Comment by pipip** [comment] 2022-01-02 22:59
Thank you so much for the update. 
The docker version is missing gcc
`Running setup.py install for pycryptodome: finished with status 'error'
copying lib/Crypto/Math/_IntegerGMP.pyi -> build/lib.linux-x86_64-3.10/Crypto/Math
    running build_ext
    building 'Crypto.Hash._MD2' extension
    creating build/temp.linux-x86_64-3.10
    creating build/temp.linux-x86_64-3.10/src
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -Isrc/ -I/usr/local/include/python3.10 -c src/MD2.c -o build/temp.linux-x86_64-3.10/src/MD2.o
    error: command 'gcc' failed: No such file or directory`

**Comment by PiotrMachowski** [comment] 2022-01-02 23:01
@pipip whoops, I haven't tested it with docker. I will fix it soon. Thank you!

**Comment by pipip** [comment] 2022-01-02 23:13
> @pipip whoops, I haven't tested it with docker. I will fix it soon. Thank you!

Thanks for the fast reply. No worries, the fix itself works great. Thanks

To fix the Dockerfile I just added: `RUN apk add build-base` before RUN pip3...

**Comment by PiotrMachowski** [comment] 2022-01-02 23:53
@pipip ok, I have fixed it + finally added GitHub action for release 👍

**Comment by N3rdix** [comment] 2022-01-03 06:25
I can confirm it’s working as expected, thanks for the quick resolution

**Comment by Tamsy** [comment] 2022-01-03 06:37
Thank you for the quick fix, Piotr 

All back to normal now and getting the tokens of my vacuums is working again like before. Excellent work!

**Comment by digitalit** [comment] 2022-01-03 14:25
Working again. Thank you Piotr
